Feat/update cosmos and use profile config
zkan/data-engineering-bootcamp pull request #12
Opened 2024-03-07 00:22 UTC by lifnaja

-

2024-03-10 01:05 UTC, zkan requested changes

2024-03-10 01:05 UTC, zkan commented on 05-analytics-engineering/scheduling-dbt/docker-compose.yaml
> +    - ${AIRFLOW_PROJ_DIR:-.}/dbt:/opt/airflow/dbt
@lifnaja ฝากเอาตรงนี้ออกให้หน่อยครับ เดี๋ยวพี่ให้คนเรียนเพิ่มเข้ามาเอง 😃

2024-03-10 01:22 UTC, zkan commented
@atbee @lifnaja ช่วยลอง

1. อัพเกรด Airflow เป็น 2.8.1
2. dbt เป็นเวอร์ชั่นล่าสุด
3. แล้วก็ใช้ `airflow-provider-great-expectations==0.2.7` แทน `great-expectations` ตัวเดิมหน่อย

2024-03-10 01:49 UTC, atbee commented
<img width="1437" alt="image" src="https://github.com/zkan/data-engineering-bootcamp/assets/39379609/275af7be-214f-4a28-b818-1391bf14c6e5">
@kan ลองแล้วดูดีครับ

2024-03-13 01:08 UTC, zkan approved these changes

2024-03-13 01:08 UTC, merged